#ifndef COMMANDLISTENER_GLOBAL_H
#define COMMANDLISTENER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COMMANDLISTENER_LIB
# define COMMANDLISTENER_EXPORT Q_DECL_EXPORT
#else
# define COMMANDLISTENER_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMANDLISTENER_GLOBAL_H
